name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18, 20, 22]
        # 查看支持的 Node.js 版本：https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4

    - name: Setup pnpm with Node.js ${{ matrix.node-version }}
      uses: pnpm/action-setup@v2
      with:
        node-version: ${{ matrix.node-version }}  # 设置 Node.js 版本
        version: 8.6.13  # 指定您需要的 pnpm 版本
        run_install: false  # 禁用自动运行 pnpm install
        cache: true  # 启用 pnpm 缓存

    - name: Install dependencies
      run: pnpm install

    - name: Run tests
      run: pnpm run test

    - name: Build project
      run: pnpm run build

    - name: Lint code
      run: pnpm run lint

    - name: Check type
      run: pnpm run type-check