name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js and pnpm cache
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: "pnpm"

    - name: Install dependencies
      run: pnpm install

    - name: Run tests
      run: pnpm run test

    - name: Build project
      run: pnpm run build

    - name: Lint code
      run: pnpm run lint

    - name: Check type
      run: pnpm run type-check